services:
  base:
    build:
      context: ./docker/base
      tags:
        - "tinyml:latest"
    image: tinyml:latest
    
  tinyml-cpu:
    init: true
    image: tinyml:latest
    ports:
      - "18888:8888" # jupyter
    volumes:
      - ./workplace:/opt/workplace
    expose:
      - "8888" 
      
  tinyml-gpu:
    init: true
    image: interactive_book:base
    ports:
      - "18888:8888" # jupyter
    volumes:
      - ./workplace:/opt/workplace
    expose:
      - "8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
